### ISSUE TITLE
Specific questions about Roomler Setup.

### ISSUE THREAD

**Issue by abreualexandre** [gjovanov/roomler#4]
Hi Goran

First, thanks for sharing this project. Its features are certainly very inspiring.
I have some doubts (not issues) that I couldn't solve them by reading the available documentation
So, I have specific questions that maybe you can comment on them (and I hope to help other people):

1) nginx: the docker run command specify the "--net = host" param and that is incompatible to "docker network connect frontend nginx". How is this should work? Default bridge mode attaching the frontend network?
2) nginx: Depeding on where you get the info (medium or github) you have two "conf.d" nginx conf files (roomler.live.conf and janus.roomler.live.conf). In practice, you can't have both running at the same time because they bind on the same port, do I have to run both?
3) nginx: In the proxy_pass (janus.roomler.live.conf), shoud I replace "janus:8080" to the IP addr of the host (since Janus is running on host mode)? Also proxy_pass in roomler.live.conf points to "roomler:3000", should I do the same?
4) roomler: can I skip the *_KEYS env vars to test only the local auth?
5) I started the docker run on roomler but the syntax is different from medium and github Readme. On github there is a port mapping -p "8082:3000" but not in Medium. Can I start this container basically setting the API_URL, DB_CONN, WS_SCALEOUT_*? JANUS_URL is needed? Port mapping is needed?

I'm still trying to make this works, but until now I got "502 bad gateway" from NGINX after point the browser to https://mydomain.com.

The containers are like this:

[root@lab]# docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                      NAMES
474433614d9c        gjovanov/nginx         "nginx -g 'daemon of…"   30 seconds ago      Up 11 seconds       80/tcp, 443/tcp            nginx
778ca28ca971        gjovanov/roomler       "docker-entrypoint.s…"   15 minutes ago      Up 15 minutes       3000/tcp                   roomler
9dfe4aa21afd        gjovanov/janus-slim    "/bin/sh -c /opt/jan…"   18 minutes ago      Up 18 minutes                                  janus
8c84e5a2e2aa        bitnami/redis:latest   "/opt/bitnami/script…"   20 minutes ago      Up 20 minutes       0.0.0.0:6379->6379/tcp     redis
61d54efb588c        mongo                  "docker-entrypoint.s…"   23 minutes ago      Up 23 minutes       0.0.0.0:27017->27017/tcp   mongo

Thanks in advance,
Alexandre.

**Comment by gjovanov** [comment]
Hi @abreualexandre,
these are all good questions.

As I'm quite busy today, I will strive to provide you with answers latest over this weekend.

Stay tuned.

**Comment by gjovanov** [comment]
Alright @abreualexandre , let me try to address you questions.

I will assume that you are trying to run all services (the whole stack) on a single machine with a single public IP. 

> 1. nginx: the docker run command specify the "--net = host" param and that is incompatible to "docker network connect frontend nginx". How is this should work? Default bridge mode attaching the frontend network?

Actually the nginx with --net=host was a typo, I would recommend starting it with the default port mappoing (bride network) e.g.

```bash
docker run -d --name nginx \
    --hostname nginx \
    --restart always \
    -v /path_to/nginx/nginx.conf:/etc/nginx/nginx.conf \
    -v /path_to/nginx/conf.d/:/etc/nginx/conf.d/ \
    -v /path_to/nginx/cert/:/etc/nginx/cert/ \
    -v /path_to/nginx/logs/:/etc/nginx/logs/ \
    -p 80:80 \
    -p 443:443/tcp \
    -p 443:443/udp \
    gjovanov/nginx
```

> 2. nginx: Depeding on where you get the info (medium or github) you have two "conf.d" nginx conf files (roomler.live.conf and janus.roomler.live.conf). In practice, you can't have both running at the same time because they bind on the same port, do I have to run both?

Indeed this is a bit incosistent information, but what I meant is you have two options:

1. Start Janus directly on the host network (recommended approach), so that janus is not behind NAT (no STUNT/TURN needed in janus.jcfg), but also add a reverse proxy behind nginx, to access janus HTTP/WS endpoints also via nginx. However in order to do that, since janus in `host` network, you cannot do another `docker network connect frontend janus`!!! but instead in the example `janus.roomler.live.conf` you can replace all `http://janus_r` with `http://YOUR_PUBLIC_IP`.

Effectively you get like this:

INTERNET <=bridge=> JANUS (for WebRTC)
INTERNET <=bridge=> NGINX <=PUBLIC IP=> JANUS_PUBLIC_IP:8088 / JANUS_PUBLIC_IP:8188 (for HTTP or WS)

so this is approach 1.

2. Start Janus on the `frontend` network (NGINX is also connected to), but then you will need to provide a STUN server in the `janus.jcfg`, so that you public ip address gets proper exposed for WebRTC connections Browser - Janus

Effectively you get like this:

INTERNET <=bridge=> NGINX <=frontend=> JANUS (for WebRTC) - with help of a STUN server in `janus.jcfg`
INTERNET <=bridge=> NGINX <=frontend=> JANUS:8088 / JANUS:8188 (for HTTP or WS)


Regarding Roomler, I would keep it fully behind nginx revered proxy:

INTERNET <=bridge=> NGINX <=frontend=> ROOMLER:3000 (for HTTP or WS)

> 3. nginx: In the proxy_pass (janus.roomler.live.conf), shoud I replace "janus:8080" to the IP addr of the host (since Janus is running on host mode)? Also proxy_pass in roomler.live.conf points to "roomler:3000", should I do the same?

- For JANUS as per approach 1. from above, you are Totally Correct: JANUS_PUBLIC_IP:8080!
- For ROOMLER you leave it as it is: roomler:3000

> 4. roomler: can I skip the *_KEYS env vars to test only the local auth?

Yes you can skip them. I've updated the root README.md with the section **Requred Environment variables** that explains this. Keep in mind if you skip the OAUTH keys, the social account login/register buttons will still render, but clicking on them will result in an error. This can be made to be dynamic e.g. if envs are omitted to omit the button rendering as well, but so far I haven't done this. Feel free to open a PR if would like to change this.

> 5. I started the docker run on roomler but the syntax is different from medium and github Readme. On github there is a port mapping -p "8082:3000" but not in Medium. Can I start this container basically setting the API_URL, DB_CONN, WS_SCALEOUT_*? JANUS_URL is needed? Port mapping is needed?

Addressed in last answer. But here is an example how to run it roomler in two commands:

```bash
docker run -d --name roomler \
    --hostname roomler \
    --network roomler \
    --restart always \
    -v /path_to/uploads:/ui/static/uploads \
    -e URL=https://yourdomain.com \
    -e API_URL=https://yourdomain.com \
    -e DB_CONN=mongodb://username:password@mongo/roomlerdb \
    -e JANUS_URL=wss://janus.yourdomain.com/janus \
    -e WS_SCALEOUT_ENABLED=true \
    -e WS_SCALEOUT_HOST=redis \
    -e SENDGRID_API_KEY=SECRET \
    -e TURN_URL=turns:coturn.yourdomain.com:PORT?transport=udp \
    -e TURN_USERNAME=username \
    -e TURN_PASSWORD=password \
    -e SUPER_ADMIN_EMAILS='["super_admin@gmail.com"]' \
    gjovanov/roomler

docker network connect nginx roomler
````

I hope it helps you start the full app stack.


Let me know if you have other questions.

**Comment by gjovanov** [comment]
Hey @abreualexandre ,
I haven't heard from you yet.

Did you manage to setup and start the app stack?

**Comment by abreualexandre** [comment]
Hi @gjovanov, thanks for the quick response.
Yes, I make some progress but still not able to use the stack yet.

On the main screen I got:
![image](https://user-images.githubusercontent.com/67473402/89790447-53bf1e00-daf8-11ea-80e8-72bcafb81ae7.png)

![image](https://user-images.githubusercontent.com/67473402/89790689-a8fb2f80-daf8-11ea-8821-96a6b6e9da98.png)

There is no errors in nginx container as I can see, nothing is being printed looking at the logs. I am using the default "roomler.live.conf" file.

If I change the URL to /auth/login or /auth/register I can see the frontend, but I can't register any user.

![image](https://user-images.githubusercontent.com/67473402/89791091-33439380-daf9-11ea-84be-1d4d15dfd93d.png)

Thats the same logs I can see from roomler container. If I type data on the form, I can't submit them. Nothing happens.

Blagodarya!

**Comment by gjovanov** [comment]
Hey @abreualexandre,
as we never used Roomler without OAuth, it seems like even though the OAuth registration configuration is optional, in `/api/api.js` it was still trying to register social accounts, which was causing this error.

I've pushed a fix for this.

You can try to build the docker image yourself from the latest `0.1.99` or pull the latest docker image from the hub.docker.com (version `0.1.99`) and try again.

Also you can start Roomler in development mode, to get better tracability in case of any error:

- `git clone this_repo`
- `cd roomler`
- `npm i`
- `create your .env file and put your env variables in separate row, in it in form: ENV_NAME=ENV_VALUE`
- `npm run dev:api`
- `npm run dev:ui`
- open in browser `http://localhost:3000`

**Comment by gjovanov** [comment]
Any progress on this one @abreualexandre ?

**Comment by abreualexandre** [comment]
Hi @gjovanov. 

I didn't make any progress after that.

1) I just removed the container and its image and re-run the "docker run" to update. Stop all containers and start all over again. Still facing the same issue, error 500 accessing / and unable to submit the form to do local auth.

![image](https://user-images.githubusercontent.com/67473402/90019089-52baf780-dc84-11ea-9247-8dee0678bd4a.png)

The padlock is OK but as I compared to the roomler.live it doesn't start any WS connection.

2) Also tried the source code approch and followed the guidelines pointed by you.
After both "npm run" I didn't see binding port 3000 and 3001 (I just use the same env vars from docker run)

3) Running in dev mode or production mode I got strange messages from the daemon:

[root@fortress roomler]# npm start

> roomler.live@0.1.99 start /usr/src/roomler
> if-env WS_SCALEOUT_ENABLED=true && npm run start:cluster || npm run start:single

> roomler.live@0.1.99 start:single /usr/src/roomler
> cross-env NODE_ENV=production node server/ui/index.js

> (node:48384) UnhandledPromiseRejectionWarning: Error: ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: 
> /usr/src/roomler/api/plugins/mongoose/fastify-mongoose.js
>    at Timeout._onTimeout (/usr/src/roomler/node_modules/avvio/plugin.js:122:19)
>    at ontimeout (timers.js:436:11)
>   at tryOnTimeout (timers.js:300:5)
>    at listOnTimeout (timers.js:263:5)
>  at Timer.processTimers (timers.js:223:10)
> (node:48384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing 
> inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 
> 1)
> (node:48384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections > that are not handled will terminate the Node.js process with a non-zero exit code.

Thanks.

**Comment by abreualexandre** [comment]
Hi @gjovanov. Thanks for your help, the problem was solved.

Let me try to explain what I did to fix these issues:

1) Update the container as indicated by @gjovanov. Running the 0.1.99 version.
2) I didn't run in dev mode, so the correct certificate (SSL) was needed.

My setup was wrong. I miss the FULL CHAIN certs also configured in "nginx.conf". That's why the message "unable to verify the first certificate". If you run in production mode, you must have this configured correctly. Strange things happens when this fails.

nginx.conf
[...]
ssl_certificate /etc/nginx/cert/httpd.crt; 
ssl_certificate_key /etc/nginx/cert/httpd.key; 
[...]

In "httpd.crt" the contents followed this order: cerficate, certicate_full_chan1, certificate_full_chain2. That's was my case. If I change this order, I got error regarding the priv key (saying that does not match) , so keep that in mind to avoid nginx errors.

Doing this correctly, the error pointed by WEB and also Chrome console went away (as you can see on the pictures above).
I couldn't even register a local user without this fix.

The Server Internal Error (500) when trying to access the main page also was fixed.

I am using two locations only inside nginx that I'll share below:

# For roomler!
location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://roomler:3000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 1800;
        proxy_connect_timeout 1800;
        proxy_send_timeout 1800;
        send_timeout 1800;
    }

# This one is for Janus (you need to follow the JANUS_URL that you used in "docker run")

location /janus {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_redirect off;

        proxy_pass http://JANUS_IP:8188;
    }

I hope it helps someone else.

Thanks,
Alexandre.

**Comment by gjovanov** [comment]
Thanks for clarifying @abreualexandre.
I'm glad you made it work.

**Comment by prototypeSean** [comment]
> Alright @abreualexandre , let me try to address you questions.
> 
> I will assume that you are trying to run all services (the whole stack) on a single machine with a single public IP.
> 
> > 1. nginx: the docker run command specify the "--net = host" param and that is incompatible to "docker network connect frontend nginx". How is this should work? Default bridge mode attaching the frontend network?
> 
> Actually the nginx with --net=host was a typo, I would recommend starting it with the default port mappoing (bride network) e.g.
> 
> ```shell
> docker run -d --name nginx \
>     --hostname nginx \
>     --restart always \
>     -v /path_to/nginx/nginx.conf:/etc/nginx/nginx.conf \
>     -v /path_to/nginx/conf.d/:/etc/nginx/conf.d/ \
>     -v /path_to/nginx/cert/:/etc/nginx/cert/ \
>     -v /path_to/nginx/logs/:/etc/nginx/logs/ \
>     -p 80:80 \
>     -p 443:443/tcp \
>     -p 443:443/udp \
>     gjovanov/nginx
> ```
> 
> > 1. nginx: Depeding on where you get the info (medium or github) you have two "conf.d" nginx conf files (roomler.live.conf and janus.roomler.live.conf). In practice, you can't have both running at the same time because they bind on the same port, do I have to run both?
> 
> Indeed this is a bit incosistent information, but what I meant is you have two options:
> 
> 1. Start Janus directly on the host network (recommended approach), so that janus is not behind NAT (no STUNT/TURN needed in janus.jcfg), but also add a reverse proxy behind nginx, to access janus HTTP/WS endpoints also via nginx. However in order to do that, since janus in `host` network, you cannot do another `docker network connect frontend janus`!!! but instead in the example `janus.roomler.live.conf` you can replace all `http://janus_r` with `http://YOUR_PUBLIC_IP`.
> 
> Effectively you get like this:
> 
> INTERNET <=bridge=> JANUS (for WebRTC)
> INTERNET <=bridge=> NGINX <=PUBLIC IP=> JANUS_PUBLIC_IP:8088 / JANUS_PUBLIC_IP:8188 (for HTTP or WS)
> 
> so this is approach 1.
> 
> 1. Start Janus on the `frontend` network (NGINX is also connected to), but then you will need to provide a STUN server in the `janus.jcfg`, so that you public ip address gets proper exposed for WebRTC connections Browser - Janus
> 
> Effectively you get like this:
> 
> INTERNET <=bridge=> NGINX <=frontend=> JANUS (for WebRTC) - with help of a STUN server in `janus.jcfg`
> INTERNET <=bridge=> NGINX <=frontend=> JANUS:8088 / JANUS:8188 (for HTTP or WS)
> 
> Regarding Roomler, I would keep it fully behind nginx revered proxy:
> 
> INTERNET <=bridge=> NGINX <=frontend=> ROOMLER:3000 (for HTTP or WS)
> 
> > 1. nginx: In the proxy_pass (janus.roomler.live.conf), shoud I replace "janus:8080" to the IP addr of the host (since Janus is running on host mode)? Also proxy_pass in roomler.live.conf points to "roomler:3000", should I do the same?
> 
> * For JANUS as per approach 1. from above, you are Totally Correct: JANUS_PUBLIC_IP:8080!
> * For ROOMLER you leave it as it is: roomler:3000
> 
> > 1. roomler: can I skip the *_KEYS env vars to test only the local auth?
> 
> Yes you can skip them. I've updated the root README.md with the section **Requred Environment variables** that explains this. Keep in mind if you skip the OAUTH keys, the social account login/register buttons will still render, but clicking on them will result in an error. This can be made to be dynamic e.g. if envs are omitted to omit the button rendering as well, but so far I haven't done this. Feel free to open a PR if would like to change this.
> 
> > 1. I started the docker run on roomler but the syntax is different from medium and github Readme. On github there is a port mapping -p "8082:3000" but not in Medium. Can I start this container basically setting the API_URL, DB_CONN, WS_SCALEOUT_*? JANUS_URL is needed? Port mapping is needed?
> 
> Addressed in last answer. But here is an example how to run it roomler in two commands:
> 
> ```shell
> docker run -d --name roomler \
>     --hostname roomler \
>     --network backend \
>     --restart always \
>     -v /path_to/uploads:/ui/static/uploads \
>     -e URL=https://yourdomain.com \
>     -e API_URL=https://yourdomain.com \
>     -e DB_CONN=mongodb://username:password@mongo/roomlerdb \
>     -e JANUS_URL=wss://janus.yourdomain.com/janus \
>     -e WS_SCALEOUT_ENABLED=true \
>     -e WS_SCALEOUT_HOST=redis \
>     -e SENDGRID_API_KEY=SECRET \
>     -e TURN_URL=turns:coturn.yourdomain.com:PORT?transport=udp \
>     -e TURN_USERNAME=username \
>     -e TURN_PASSWORD=password \
>     -e SUPER_ADMIN_EMAILS='["super_admin@gmail.com"]' \
>     gjovanov/roomler
> 
> docker network connect frontend roomler
> ```
> 
> I hope it helps you start the full app stack.
> 
> Let me know if you have other questions.

HI @gjovanov 
thanks for this awesome project, but I was stuck at a similar point and found this post, but confused by your insturction, 
at the Nginx config part, dose this mean the article at medium was wrong? cause you need to set 
```
 a reverse proxy behind nginx, to access janus HTTP/WS endpoints also via nginx. However in order to do that, since janus in host network, you cannot do another docker network connect frontend janus!!! but instead in the example janus.roomler.live.conf you can replace all http://janus_r with http://YOUR_PUBLIC_IP
```

but in  https://medium.com/@gjovanov/building-your-own-slack-54874bf5fd7a

you Start Janus directly on the host network, and still only config the `roomler.live.conf` and didn't provide a STUN server in the janus.jcfg ?

or did I missed something obvious? thanks for any help

**Comment by gjovanov** [comment]
Hi @prototypeSean ,
there is no single way to start the stack and it all depends on our infrastructure. Having said that, I would say for you the simplest way is to start each dependency service is one-by-one as in roomler docs:
- https://github.com/gjovanov/roomler/blob/master/docs/deps-janus.md
- https://github.com/gjovanov/roomler/blob/master/docs/deps-coturn.md
- https://github.com/gjovanov/roomler/blob/master/docs/deps-mongo.md
- https://github.com/gjovanov/roomler/blob/master/docs/deps-redis.md

and then you start roomler as explained in:
- https://github.com/gjovanov/roomler#docker-run

Keep in mind before any of the above steps you need to create two docker networks as explained in:
- https://github.com/gjovanov/roomler#docker-network

Since you have started both `janus` and `coturn` on the `host` network, and assuming they are exposed directly on the public ip, then there is no need to setup a STUN server in janus config.

This is a setup simplest and without `nginx`.


You can also use `nginx` as a reverse proxy for HTTP/WS communication with Janus and Roomler, but in the case of Janus, you need to run it with port mapping (not exposed on the host network) e.g.:

```
docker run -d \
  --name="janus" \
  --restart="always" \
  -p 7089:7088 \
  -p 7189:7188 \
  -p 8089:8088 \
  -p 8189:8188 \
  gjovanov/janus-slim
```

and add STUN in the janus.cfg, because your janus is not exposed on the public ip.

Again, there are many diff setups for installing the stack, but these are the simplest.


Hope it helps.

/GJ

**Comment by prototypeSean** [comment]
Hi @gjovanov thanks for the reply, still no luck today, and didn't know which step went wrong, maybe I could explain my steps in detail?

**Server Eniverment:**
AWS EC2 
Ubuntu 20

**My approachment:**
0. I start all service  using `docker run` and by the order in [this yml](https://github.com/gjovanov/roomler/blob/master/docker-compose.yml)

1. **Redis**
```
sudo docker run -d \
--name="redis" \
--restart=always \
-e ALLOW_EMPTY_PASSWORD=yes \
-p 6379:6379 \
--network=backend \
bitnami/redis:latest
```

2. **Mongo DB**
```
sudo docker run -d \
  --name mongo \
  --restart=always \
  -p 27017:27017 \
  -e MONGO_INITDB_ROOT_USERNAME=SuperAdmin \
  -e MONGO_INITDB_ROOT_PASSWORD=SuperAdminSecret \
  -v /home/ubuntu/roomler/mongo_data:/data/db \
  --network=backend \
  mongo
```
then get in the container to create roomlerdb
`sudo docker exec -it mongo /bin/sh`

>>> in the container >>> log in as admin
`mongo -u SuperAdmin -p SuperAdminSecret`
cerate db
`use roomlerdb`
create user
```
db.createUser(
  {
    user: "roomler",
    pwd: "super_secret",
    roles: [ { role: "readWrite", db: "roomlerdb" } ]
  }
)
```

3. **coturn**
 because I couldn't get instrumentisto/coturn working so I'm using offical image
 but is it ok?
```
sudo docker run -d \
   --name="coturn" \
   --restart="always" \
   --net=host \
        coturn/coturn -n \
          --lt-cred-mech --fingerprint \
          --no-multicast-peers \
          --cli-password=MyTopSecret \
          --no-tlsv1 \
          --no-tlsv1_1 \
          --fingerprint \
          --lt-cred-mech \
          --verbose \
          --user=SuperUser:MyTopSecret \
          --server-name=mydomainname.ddns.net \
          --realm=mydomainname.ddns.net \
          --listening-ip='$(detect-external-ip)' \
          --external-ip=**my public ip**/172.31.12.197 \
          --min-port=10200 \
          --max-port=49200
```
 
 4. **Janus**
```
sudo docker run -d \
  --name="janus" \
  --restart="always" \
  --network="host" \
  gjovanov/janus-slim
```
 
 5. **Roomler**
 not sure about `TURN_URL` 
 ```
sudo docker run -d --name roomler \
    --hostname roomler \
    --network backend \
    --restart always \
    -v /home/ubuntu/roomler/roomler_upload:/roomler/packages/ui/static/uploads \
    -e API_URL=http://mydomain_name \
    -p 8082:3000 \
    -e DB_CONN=mongodb://mongodb:27017/roomlerdb \
    -e WS_SCALEOUT_ENABLED=true \
    -e WS_SCALEOUT_HOST=redis \
    -e TURN_URL=ws://turn.mydomain_name \
    -e TURN_USERNAME=SuperUser \
    -e TURN_PASSWORD=MyTopSecret \
    -e SUPER_ADMIN_EMAILS='["myemail@gmail.com"]' \
    -e NUXT_TELEMETRY_DISABLED=1 \
    gjovanov/roomler
```
and `sudo docker network connect frontend roomler`

6. **Nginx**
cause I'm used to using certbot as ssl auto update service, so I'm using [staticfloat/nginx-certbot](https://hub.docker.com/r/staticfloat/nginx-certbot/)

conf.d/my.conf
```
server {
     listen 443 ssl;

     server_name  my_domain_name;

     ssl_certificate /etc/letsencrypt/live/my_domain_name/fullchain.pem;
     ssl_certificate_key /etc/letsencrypt/live/my_domain_name/privkey.pem;

    location / {
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   Host      $http_host;
        proxy_pass         http://roomler:3000;

        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_read_timeout 1800;
        proxy_connect_timeout 1800;
        proxy_send_timeout 1800;
        send_timeout 1800;

     }
}
```

and
```
sudo sudo docker run -d --name nginx \
    --hostname nginx \
    --restart always \
    -v /home/ubuntu/roomler/conf.d:/etc/nginx/user.conf.d:ro \
    -v /home/ubuntu/roomler/nginx/letsencrypt/:/etc/letsencrypt \
    -v /home/ubuntu/roomler/nginx/logs/:/etc/nginx/logs/ \
    -p 80:80 \
    -p 443:443/tcp \
    -p 443:443/udp \
    -e CERTBOT_EMAIL=denniskao1986@gmail.com \
    --net=bridge \
    staticfloat/nginx-certbot
```

finally `sudo docker network connect frontend nginx`

after all above steps, I got 502 Bad Gateway in browser and 
errors in roomler and nginx

roomler
```
0|roomler  | ERROR: Error: No subject set in vapidDetails.subject.
0|roomler  | You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
0|roomler  | Error: ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: /roomler/packages/api/plugins/mongoose/fastify-mongoose.js. You may have forgotten to call 'done' function or to resolve a Promise
0|roomler  |     at Timeout._onTimeout (/roomler/node_modules/avvio/plugin.js:122:19)
0|roomler  |     at listOnTimeout (internal/timers.js:551:17)
0|roomler  |     at processTimers (internal/timers.js:494:7)
```

nginx
```
2021/05/05 08:47:48 [error] 38#38: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 36.228.21.250, server: mydomain.ddns.net, request: "GET / HTTP/1.1", upstream: "http://172.18.0.2:3000/", host: "mydomain.ddns.net"
36.228.21.250 - - [05/May/2021:08:47:48 +0000] "GET / HTTP/1.1" 502 559 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36" "-"
```

**Comment by gjovanov** [comment]
ok we have some progress @prototypeSean .

The first error with `vapidDetails` seems to be related to `web-push` notifications, needing the private and public key generated. You can generate them as explained here:
- https://github.com/gjovanov/roomler/blob/master/docs/env.md#push-notifications-optional

Even though I've written they are optional, it seems that they are currently made mandatory. Sorry for that, I will need to update the docs. In the meanwhile you need to add:
- WEB_PUSH_CONTACT - e.g. "mailto: your_contact_email@gmail.com"
- WEB_PUSH_PUBLISH_KEY - Your VAPID public key
- WEB_PUSH_PRIVATE_KEY - Your VAPID private key

So I assume until roomler is not started (like the this error), you will be sees also error via nginx.

So pls try fixing the above first and see if at least roomler start successfully.

**Comment by prototypeSean** [comment]
Hi, @gjovanov I've made some progress today, but still stuck.

first, I figure out this part of the error was my mistake: 
```
0|roomler  | Error: ERR_AVVIO_PLUGIN_TIMEOUT: plugin did not start in time: /roomler/packages/api/plugins/mongoose/fastify-mongoose.js. You may have forgotten to call 'done' function or to resolve a Promise
0|roomler  |     at Timeout._onTimeout (/roomler/node_modules/avvio/plugin.js:122:19)

```
that my 
`-e DB_CONN=mongodb://mongodb:27017/roomlerdb`
should be
`-e DB_CONN=mongo://mongodb:27017/roomlerdb`

after changed that, I've started to receive different error looks like a connection error between roomler <--> redis
```
0|roomler  | [ioredis] Unhandled error event: Error: connect ECONNREFUSED 127.0.0.1:6379
0|roomler  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16)
```
**looks like it's trying to connect to localhost in the same container, but redis is in another container (same network) ?**


and my Docker current status
```
staticfloat/nginx-certbot   "/bin/bash /scripts/…"   56 seconds ago       Restarting (0) 9 seconds ago                                                   nginx
gjovanov/roomler            "docker-entrypoint.s…"   About a minute ago   Up About a minute              0.0.0.0:8082->3000/tcp, :::8082->3000/tcp       roomler
bitnami/redis:latest        "/opt/bitnami/script…"   40 minutes ago       Up 40 minutes                  0.0.0.0:6379->6379/tcp, :::6379->6379/tcp       redis
gjovanov/janus-slim         "/bin/sh -c /opt/jan…"   24 hours ago         Up 24 hours                                                                    janus
mongo                       "docker-entrypoint.s…"   28 hours ago         Up 28 hours                    0.0.0.0:27017->27017/tcp, :::27017->27017/tcp   mongo
coturn/coturn               "docker-entrypoint.s…"   29 hours ago         Up 29 hours                                                                    coturn
```

I've checked my docker network by `docker network inspect` to make sure
"backend" containers {mongo},  {redis},  {roomler}
"frontend" containers {roomler},  {nginx}(but faling so keep restarting)
"host" containers {coturn}, {janus},

**Comment by prototypeSean** [comment]
Oh!  I figured it out,  it another [Environment variables](https://github.com/gjovanov/roomler/blob/c45acacf48c732ed73f660517a2674e8e0f95d55/docs/env.md#web-sockets-optional)

that need to set,

```
-e WS_SCALEOUT_ENABLED=true
-e WS_SCALEOUT_HOST=redis
```
or [ioredis] will try to connect redis by default local:6379
set those Environment variables to change host to "redis"

**Comment by gjovanov** [comment]
Hey @prototypeSean ,
yes indeed the redis env vars need to be setup.

Btw I forgot to mention yesterday, but I'm not sure how the official `coturn/coturn` docker image work and whether your can pass `args` the same the same way as you would do with `instrumentisto/coturn` hence I recommend you test your coturn instance following the answer here:
- https://stackoverflow.com/questions/28772212/stun-turn-server-connectivity-test

You can create as imple `index.html` page and put declaration of the `checkTURNServer` function as well as calling it inside a `<script type="javascript">... </script>` with username, password and IP:port of your coturn to see if it works.

**Comment by prototypeSean** [comment]
Hi @gjovanov,
Thanks for reminding me, I've tried coturn on https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice
and got a  "Done" status, and thought it's reachable from the public network? but not sure what the error below means, 
![screenshot](https://i.imgur.com/EZMnsFL.png)

and currently, I'm stucking on maybe JS part of the project? since last week, my host and first-page render looks fine on chrome but got multiple issues

- firefox failed and show connection fail blank page
- my WebSocket looks failing, and not sure where I could start to debug
- no where to register the user? I didn't fill in the third part auth env variables cause I thought It could be optional? 
sorry for the massive questions but I really don't know where to start debugging
![error screen](https://i.imgur.com/vxjE3jp.png)
